<?php
/**
 * layout.phtml
 *
 * @copyright Copyright © 2015 cloud-nemo
 * @author    cloud-nemo
 */
echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
    <link href="css/ui-dark.css" rel="stylesheet">
    <script type="application/javascript" src="js/base.js"></script>
    <script type="application/javascript" src="js/ui.js"></script>
</head>
<body>
</body>
</html>