<?php
/**
 * layout.phtml
 *
 * @copyright Copyright © 2015 cloud-nemo
 * @author    cloud-nemo
 */
echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
    <?php
    // Metas
    echo $this->headTitle();
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    // Styles
    echo $this->headLink(
        array(
            'rel' => 'shortcut icon',
            'type' => 'image/png',
            'href' => $this->basePath() . '/image/favicon.png'))
        ->prependStylesheet($this->basePath('css/layout.css'))
        ->prependStylesheet($this->basePath('css/ui-dark.css'));
    // Scripts
    echo $this->headScript()
        ->appendFile($this->basePath('js/jquery-2.1.4.js'))
        ->appendFile($this->basePath('js/base.js'))
        ->appendFile($this->basePath('js/ui.js'))
        ->appendFile($this->basePath('js/navigation.js'));
    ?>
</head>
<body>
<div id="createNavBar" data-win-control="WinJS.UI.NavBar" data-win-options="{
    placement: 'top',
    oninvoked: Navi.navBarInvoked
}">
    <div data-win-control="WinJS.UI.NavBarContainer">
        <div data-win-control="WinJS.UI.NavBarCommand"
             data-win-options="{ label: 'Home', icon: 'home', location:'<?php echo $this->basePath() ?>'}"></div>
        <div data-win-control="WinJS.UI.NavBarCommand"
             data-win-options="{ label: 'World', icon: 'world', location:'<?php echo $this->basePath('world') ?>'
             }"></div>
        <div data-win-control="WinJS.UI.NavBarCommand"
             data-win-options="{ label: 'World-Map', icon: 'map', location:'<?php echo $this->basePath('world/map')
             ?>' }"></div>
    </div>
</div><!-- /.navbar -->
<div class="container">
    <div id="pageContent">
        <?php echo $this->content; ?>
        <br/>
        <p id="status"></p>
    </div>
</div><!-- /.container -->
<footer>
    <hr><p>&copy; 2015<?php
        echo ('2015' !== date('Y')) ? ' - ' . date('Y') : null ?> | Cloud Nemo : <?php
        echo $this->translate('All rights reversed.') ?> | Powered by Zend Technologies Ltd.<?php
        echo (APPLICATION_ENV == 'local') ? ' | ZF-' . Zend\Version\Version::VERSION : null
    ?>
    </p>
</footer><!-- /footer -->
<?php echo $this->inlineScript() ?><!-- /script -->
</body>
</html>