<?php
/**
 * layout.phtml
 *
 * @copyright Copyright © 2015 cloud-nemo
 * @author    cloud-nemo
 */
echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
    <?php
    // Metas
    echo $this->headTitle('Test-Project')
        ->setSeparator(' - ')->setAutoEscape(false);
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    // Styles
    echo $this->headLink(
        array(
            'rel' => 'shortcut icon',
            'type' => 'image/png',
            'href' => $this->basePath() . '/image/favicon.png'))
        ->prependStylesheet($this->basePath('css/ui-dark.css'))
        ->prependStylesheet($this->basePath('css/layout.css'));
    // Scripts
    echo $this->headScript()
        ->appendFile($this->basePath('js/base.js'))
        ->appendFile($this->basePath('js/ui.js'))
    ?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                </li>
            </ul>
        </div><!-- /.nav-collapse -->
    </div>
</nav><!-- /nav -->
<div class="container">
    <?php echo $this->content; ?>

</div><!-- /.container -->
<footer>
    <hr><p>&copy; <?php echo date('Y') ?> | Cloud Nemo : <?php echo $this->translate('All rights reversed.') ?>
        | Powered by Zend Technologies Ltd. | ZF-<?php echo (APPLICATION_ENV == 'local') ?
            Zend\Version\Version::VERSION : null ?>
    </p>
</footer><!-- /footer -->
<?php echo $this->inlineScript() ?><!-- /script -->
</body>
</html>